---
title: "Managing Pathways"
author: "Michelle DeMers"
date: "2025-10-18"
output: pdf_document
---
```{r setup, include=FALSE}
setwd("/Users/michelle/Documents/DOSTraits/")
library(tidyr)
library(dplyr)
library(ggplot2)
library("seqinr")
library(ggtree)
library(ggtreeExtra)
library(ggnewscale)
library(ggstatsplot)
library(ggridges)
library(indicspecies)
library(pheatmap)
library(RColorBrewer)
library("NatParksPalettes")
library(nationalparkcolors)
library(ggpubr)
library(patchwork)
library(ggridges)

# setting color palettes
c(natparks.pals("IguazuFalls", 6))
# the basis palette above
# the actual colors below
values3 <- c("#2F397A","#415521","#5A8093")
values6 <- c("#2F397A", "#415521", "#5A8093", "#9399bd", "#9fb6c2", "#c0d998")
values9 <- c( "#dce0fa","#868DBA","#2F397A", "#d0eaf7","#95B5C5","#5A8093","#ebf7d7", "#96A67C" ,"#415521")
tcols <- c("#d3004b","#8b373f","#ff4f60","#ac6863","#b80020","#fdb5a0","#cb6300","#e7c087","#f2b707","#cbcd29","#475907","#8ab200","#95d86c","#008014","#44c442","#01e1a1","#00956e","#009083","#0085e8","#0270f9","#aa79ff","#7431a2","#eb8dff","#ffa8f2","#ff7be8","#ff8bd9","#c30099","#7e486b","#962166","#ffa1c0")
df <- read.csv("genome_summary_ELM_2.csv")
names(tcols) <- sort(unique(df$taxa_elm)[1:30])
```
# Genomes
Import all of our files and get the right number of genomes in these files.
```{r}
si_lifestyle <- read.csv("new_filtered_SA/Sulfate Assimilationprocessed_above75genomecompletion_wlifestyle.csv")
si_lifestyle <- si_lifestyle[,c(1,23)]
names(si_lifestyle)[1] <- "Genome"
# remove genomes with no phyla (no GTDB taxonomy)
names_ids <- read.csv("genome_summary_ELM_2.csv")
names_ids <- names_ids[-(which(is.na(names_ids$Phyla))),]
names_ids <- names_ids[,c(1,56)]
names(names_ids)[1] <- "Genome"
# remove genomes that have no hits in any pathways
maxcompletion <- read.csv("kofam_results/summary_max_table.csv", row.names = 1)
maxcompletion <- maxcompletion[-(which(rowSums(maxcompletion)== 0)),]
maxcompletion <- cbind(row.names(maxcompletion), maxcompletion)
names(maxcompletion)[1] <- "Genome"
#select the overlap to get 15969
names_id_filtered <- names_ids[which(names_ids$Genome %in% maxcompletion$Genome),]
nrow(names_id_filtered)
# check some numbers
head(names_id_filtered %>% group_by(taxa_elm) %>% summarize(n= n()), n = 30L)

```
Checking some numbers, by pathway
```{r}
# Cysteine biosynthesis
test_df <- read.csv("kofam_results/Cysteine Biosynthesisprocessed_above75genomecompletion.csv")
test_df <- test_df %>% filter(X %in% names_id_filtered$Genome)
test_df %>% filter(MaxCompletion== 1) %>% summarise(count_s1 = sum(Subpathway1), count_s2 = sum(Subpathway2), count_s3 = sum(Subpathway3), count_s4 = sum(Subpathway4), count_s5 = sum(Subpathway5))
# looks like subpathway 1 is the pathway that is getting most of the genomes to the completion of the pathway
test_df %>% filter(Subpathway1 == 0.5) %>% summarise(count_step1 = sum(Step1), count_step2 = sum(Step2))
# Therefore, not all of the genomes are incomplete for the same reason. What should we do? 
test_df %>% select(Step1, Step2, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5)
# no explicit taxonomic signal...if they have one step, should they just have the other for subpathway 1?
# michelle's vote: leave the incompletes as is or turn them to complete.

```

```{r}
# Cysteine.Degradation
# this pathway is either a two step reaction or a one step reaction
test_df <- read.csv("kofam_results/Cysteine Degradationprocessed_above75genomecompletion.csv")
test_df <- test_df %>% filter(X %in% names_id_filtered$Genome)
test_df %>% filter(MaxCompletion== 1) %>% summarise(count_step1 = sum(Step1), count_step2 = sum(Step2), count_step3 = sum(Step3), count_step4 = sum(Step4), count_step5 = sum(Step5))
# mostly being completed by step 5, which subpathway 4
test_df %>% filter(MaxCompletion != 1) %>% summarise(count_step1 = sum(Step1), count_step2 = sum(Step2), count_step3 = sum(Step3), count_step4 = sum(Step4), count_step5 = sum(Step5))
test_df %>% select(Step1, Step2, Step3, Step4, Step5, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5)
# Therefore, not all of the genomes are incomplete for the same reason, besides the fact that they do not have the one-step pathways. What should we do?
# michelle's vote: leave the incompletes as is or turn them to complete.
```

```{r}
# Methionine.Synthesis
# these are long pathways, an average of ~4 steps per subpathway option
test_df <- read.csv("kofam_results/Methionine Synthesisprocessed_above75genomecompletion.csv")
test_df <- test_df %>% filter(X %in% names_id_filtered$Genome)
test_df %>% filter(Subpathway1 ==1 ) %>% summarise(n = n())
test_df %>% filter(Subpathway2 ==1 ) %>% summarise(n = n())
test_df %>% filter(Subpathway3 ==1 ) %>% summarise(n = n())
#7,251
test_df %>% filter(Subpathway4 ==1 ) %>% summarise(n = n())
test_df %>% filter(Subpathway5 ==1 ) %>% summarise(n = n())
test_df %>% filter(Subpathway6 ==1 ) %>% summarise(n = n())
# looks like most are using subpathway 3 (3 steps) or subpathway 6 (6 steps)
# because subpathway 6 contains all three steps of subpathway 3, in order, we'll just consider subpathway 3
# subpathway 3
test_df %>% summarise(count_step1 = sum(Step7), count_step2 = sum(Step8), count_step3 = sum(Step4))
# looks like it isn't necessaryily the same step everytime being absent; step 7 and step 4 are lower in abundance but they're still in 10,000 genomes each. What do we do here?
# let's see how many genomes are just missing one step
test_df %>% filter(Subpathway3 != 1 & Subpathway3 > 0.5) %>% summarise(n=n())
# 5,197
test_df %>% filter(Subpathway3 != 0 & Subpathway3 < 0.5) %>% summarise(n=n())
# 3,127
test_df %>% filter(Subpathway3 == 0 ) %>% summarise(n=n())
# 394
# let's see how this is distributed across taxa
test_df %>% select(Step7, Step8, Step4, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5)
test_df %>% filter(MaxCompletion < 1 & MaxCompletion > 0.5) %>% select(Step7, Step8, Step4, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5)
# the figure above makes it look like many genomes have step 7 and 8 but not 4. Let's see how many that is relative to the other options
test_df %>% select(Step7, Step8, Step4, Group) %>% filter(Step4 == 0 & Step7 ==1 & Step8 ==1) %>% summarise(n = n()) #3,000 of the 5,000 genomes at 2/3 complete 
test_df %>% select(Step7, Step8, Step4, Group) %>% filter(Step4 == 1 & Step7 ==0 & Step8 ==1) %>% summarise(n = n()) #~2000 genomes 5,000
test_df %>% select(Step7, Step8, Step4, Group) %>% filter(Step4 == 1 & Step7 ==1 & Step8 ==0) %>% summarise(n = n()) # very few genomes
# what do we do here? should we give 2/3 complete a present? Let's see how many are ==2/3 versus >2/3 but less than 1
test_df %>% filter(MaxCompletion <1 & MaxCompletion > .66) %>% summarise(n = n())
# 5,627 genomes; not many more than just those that are 2/3 complete from subpathway 3
test_df %>% mutate(MaxCompletion = factor(MaxCompletion)) %>% group_by(MaxCompletion)%>% summarise(n = n())
# dadabacteria are pretty distinct in their lack of hits for step 7 and 8?
# michelle's vote: maybe change the 2/3 complete to fully complete, and leave the rest as is. Could go as far to say if you have greater than 2/3 completion (because some genomes may be using a different pathway and be 3/4 complete), then that would get you a present for methionine salvage.
test_df <- merge(test_df, si_lifestyle, by.x = "X", by.y = "Genome")
test_df %>% group_by(Lifestyle) %>% filter(MaxCompletion > .66) %>% summarise(n = n())
# whats the canonical pathway?
# is it known that there is a 3 step?
```

```{r}
# Glutathione.Synthesis
# just a two step pathway
test_df <- read.csv("kofam_results/Glutathione Synthesisprocessed_above75genomecompletion.csv")
test_df <- test_df %>% filter(X %in% names_id_filtered$Genome) %>% select(X,Step1, Step2, Subpathway1,MaxCompletion,Group,Completion,Type)
test_df %>% filter(Subpathway1 == 0.5) %>% summarise(count_step1 = sum(Step1), count_step2 = sum(Step2))
test_df %>% select(Step1, Step2, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5)
test_df %>% filter(MaxCompletion == 0.5) %>% select(Step1, Step2, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5)
test_df %>% filter(Step1 == 1 & Step2 == 0) %>% summarise(n = n()) #1400 genomes
test_df %>% filter(Step1 == 0 & Step2 == 1) %>% summarise(n = n()) #1900 genomes
# Therefore, not all of the genomes are incomplete for the same reason.
# what do we do?
# are patescibacteria just missing a lot of things? to check in max completion?
# michelle's vote: leave the incompletes as is.
```

```{r}
# Methionine.Degradation
# this is a 3 step process; only one subpathway
test_df <- read.csv("kofam_results/Methionine Degradationprocessed_above75genomecompletion.csv")
# remove step4 and 5, they are not used
test_df <- test_df %>% filter(X %in% names_id_filtered$Genome) %>% select(X,Step1, Step2, Step3, Subpathway1,MaxCompletion,Group,Completion,Type)
test_df %>% filter(MaxCompletion == 1) %>% summarise(n = n())
test_df %>% filter(MaxCompletion < 1 & MaxCompletion > 0.5) %>% summarise(n = n()) #10,000 
# are all 10000 missing the same one step?
test_df %>% filter(Step1 == 0 & Step2 ==1 & Step3 ==1) %>% summarise(n = n()) #187 of the 10,000 genomes at 2/3 complete 
test_df %>% filter(Step1== 1 & Step2 ==0 & Step3 ==1) %>% summarise(n = n()) #9,500 genomes 10,000
test_df %>% filter(MaxCompletion > 0.5 & MaxCompletion < 1) %>% select(Step1, Step2, Step3, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5) # see how widespread missing step 2 is!
test_df %>% filter(Step1 == 1 & Step2 ==1 & Step3 ==0) %>% summarise(n = n()) # 500 genomes
# should we make it so that if you are missing step 2 only, we just give you the pathway?
# michelle's vote: If you are only missing step 2 of the three steps, just make you complete. So, remove step two from the steps.
```

```{r}
# Choline.O.sulfate.Degradation
# 3 steps pathway, only one subpathway
test_df <- read.csv("kofam_results/Choline-O-sulfate Degradationprocessed_above75genomecompletion.csv")
test_df <- test_df %>% filter(X %in% names_id_filtered$Genome)
# look at distribution of incomplete ones
test_df %>% filter(MaxCompletion > 0.5 & MaxCompletion < 1) %>% select(Step1, Step2, Step3, Group) %>% pivot_longer(cols = where(is.numeric)) %>% ggplot(aes(x = name, y = value)) + geom_boxplot() + geom_point(position = "jitter", alpha = 0.1) + facet_wrap(Group~., nrow = 5) # is missing step 3 common?
test_df %>% filter(MaxCompletion < 1 & MaxCompletion > 0.5) %>% summarise(n = n()) #3000
test_df %>% filter(MaxCompletion >0 & MaxCompletion < 0.5) %>% summarise(n = n()) #5000
# more common to be missing two steps than just one, so no
test_df %>% filter(Step1 == 0 & Step2 ==0 & Step3 ==1) %>% summarise(n = n()) #260
test_df %>% filter(Step1== 1 & Step2 ==0 & Step3 ==0) %>% summarise(n = n()) #2287
test_df %>% filter(Step1 == 0 & Step2 ==1 & Step3 ==0) %>% summarise(n = n()) #3200
#what do we do here?
# michelle's vote: leave the incompletes as is, because you are missing 2/3 steps, and it's not the same steps you are missing; only ~2000 have the first step, so maybe we turn those to complete but otherwise, no?
```